import Sidebar from '@/components/Navbar'
import './globals.css'
import { Signika } from 'next/font/google'
import { Toaster } from '@/components/ui/toaster'

const font = Signika({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Sidebar>
          {children}
          <Toaster />
        </Sidebar>
      </body>
    </html>
  )
}
